
define: &img_shape [512, 512]

logger:
  project: Grading-DiabeticRetinopathy-Comparisons-V2

data:
  data_dir: /home/tmp/clpla/data/eyepacs/
  img_size: *img_shape
  batch_size: 14
  valid_size: 4000
  num_workers: auto
  use_cache: True
  cache_option: disk  # or memory

model:
  architecture: mobilenet_v3large
  num_classes: 5
  pretrained: True
  img_size: *img_shape

training:
  lr: 0.00003
  as_regression: True
  optimizer:
    betas: [.9, .999]
    weight_decay: 0.0005
  mixup:
    mixup_alpha: 0
    cutmix_alpha: 0
    cutmix_minmax:
    prob: 1.0
    switch_prob: 0.5
    mode: batch
    label_smoothing: 0.1
    num_classes: 5

trainer:
  accumulate_grad_batches: 4
  accelerator: gpu
  deterministic: False
  devices: auto
  max_epochs: 100
  precision: 16-mixed
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 2
  fast_dev_run: False
