
define: &img_shape [512, 512]

logger:
  project: Grading-DiabeticRetinopathy-Comparisons-V3

datasets:
  eyepacs: /home/tmp/clpla/data/classification/eyepacs/
  aptos: /home/tmp/clpla/data/classification/aptos/
  idrid: /home/tmp/clpla/data/classification/IDRID/B. Disease Grading/ 
  ddr: /home/tmp/clpla/data/classification/DDR-dataset/DR_grading/

data:
  img_size: *img_shape
  batch_size: 24
  valid_size: 0.2
  num_workers: 12
  use_cache: True
  cache_option: disk  # or memory

model:
  architecture: mobilenet_v3large
  num_classes: 5
  pretrained: True
  img_size: *img_shape

training:
  lr: 0.0001
  as_regression: True
  optimizer:
    betas: [.9, .999]
    weight_decay: 0.0005
  mixup:
    mixup_alpha: 0.5
    cutmix_alpha: 0.5
    prob: 1.0
    switch_prob: 0.5
    mode: batch
    label_smoothing: 0.1
    num_classes: 5
  swa:
    swa_lrs: 0.0001
  ema:
    decay: 0.999

trainer:
  accumulate_grad_batches: 4
  accelerator: gpu
  deterministic: False
  devices: auto
  max_epochs: 200
  precision: 16-mixed
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 2
  fast_dev_run: False
